### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by orangorangorang** [asindico/callsplugin#2]
Hi, I used your plugin at a new fresh project, but when I try to console log it, it crash at Line 9 at 

cordova.exec(function(winParam) {callback(winParam)},

Can you please help me by sending the simple project of logging android calls? thanks !!

Note : I check my apps, it doesnt ask for permission to have call log, is it normal?

**Comment by aboobakkar** [comment]
same issue for me

**Comment by aboobakkar** [comment]
App crash issue not solved

**Comment by asindico** [comment]
Hi, have you added the `<uses-permission android:name="android.permission.READ_CALL_LOG" /> `permission to your app manifest?
