### ISSUE TITLE
App Crash 

### ISSUE THREAD

**Issue by aboobakkar** [asindico/callsplugin#4]
i have created an meteor cordova hybrid application. also installed calls plugin  and run the application ,
console messages are 

> CallsPlugin.js: is created

> getCALLS
next time app was crashed. 
OS version is Android 5.1 and android 7.0 are used.same effect

**Comment by asindico** [comment]
Hi, have you added the `<uses-permission android:name="android.permission.READ_CALL_LOG" /> `permission to your app manifest?

**Comment by asindico** [comment]
did it solve the issue?
